# Any python files modifed but no test files modified
add-test-cases:
- all:
  - changed-files:
    - any-glob-to-any-file: 'saashq/**/*.py'
    - all-globs-to-all-files: '!saashq/**/test*.py'

# Add 'release' label to any PR that is opened against the `main` branch
release:
 - base-branch: ['^version-\d+$']
