[[Blogger]]
full_name = "_Test Blogger"
short_name = "_Test Blogger"

[[Blogger]]
full_name = "_Test Blogger 1"
short_name = "_Test Blogger 1"

[[Blogger]]
full_name = "_Test Blogger 2"
short_name = "_Test Blogger 2"

