[[Event]]
subject = "_Test Event 1"
starts_on = "2014-01-01"
event_type = "Public"
creation = "2014-01-01"

[[Event]]
subject = "_Test Event 2"
starts_on = "2014-01-01"
event_type = "Private"
creation = "2014-01-01"

[[Event]]
subject = "_Test Event 3"
starts_on = "2014-02-01"
event_type = "Private"
creation = "2014-02-01"

