[[User]]
email = "test@example.com"
enabled = 1
first_name = "_Test"
new_password = "Eastern_43A1W"
[[User.roles]]
doctype = "Has Role"
parentfield = "roles"
role = "_Test Role"

[[User.roles]]
doctype = "Has Role"
parentfield = "roles"
role = "System Manager"


[[User]]
email = "test1@example.com"
first_name = "_Test1"
new_password = "Eastern_43A1W"

[[User]]
email = "test2@example.com"
first_name = "_Test2"
new_password = "Eastern_43A1W"
enabled = 1

[[User]]
email = "test3@example.com"
first_name = "_Test3"
new_password = "Eastern_43A1W"
enabled = 1

[[User]]
email = "test4@example.com"
first_name = "_Test4"
new_password = "Eastern_43A1W"
enabled = 1

[[User]]
email = "test'5@example.com"
first_name = "_Test'5"
new_password = "Eastern_43A1W"
enabled = 1

[[User]]
email = "testperm@example.com"
first_name = "_Test Perm"
new_password = "Eastern_43A1W"
enabled = 1

[[User]]
email = "testdelete@example.com"
enabled = 1
first_name = "_Test"
new_password = "Eastern_43A1W"
[[User.roles]]
doctype = "Has Role"
parentfield = "roles"
role = "_Test Role 2"

[[User.roles]]
doctype = "Has Role"
parentfield = "roles"
role = "System Manager"


[[User]]
email = "testpassword@example.com"
enabled = 1
first_name = "_Test"
new_password = "Eastern_43A1W"
[[User.roles]]
doctype = "Has Role"
parentfield = "roles"
role = "System Manager"


