name: Downstream

on:
  workflow_dispatch:

jobs:
  dispatch:
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        repo:
          - saashq/erpnexus
          - saashq/lending
          - saashq/hrms
    steps:
      - name: Dispatch Downstream CI (if supported)
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.CI_PAT }}
          repository: ${{ matrix.repo }}
          event-type: saashq-framework-change
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'
